---
title: 'Sesión 1: 2018/01/15'
output:
  html_document:
    df_print: paged
---

_175904 - Jorge III Altamirano Astorga_

```{r message=FALSE, warning=FALSE, include=FALSE}
library(tidyverse)
library(ggplot2)
library(arules)
```


```{r}
data(Groceries) # del paquete arules
lista_mb <- as(Groceries, 'list')
num_items <- sapply(lista_mb, length)
qplot(num_items, binwidth=1)  
```

```{r}
canastas_nest <- data_frame(canasta_id = 1:length(lista_mb),
                      articulos = lista_mb) 
canastas <- canastas_nest %>% unnest
num_canastas <- nrow(canastas_nest)
articulos_frec <- canastas %>% group_by(articulos) %>%
                  summarise(n  = n()) %>%
                  mutate(prop = n / num_canastas) %>%
                  arrange(desc(n))
#DT::datatable
(articulos_frec %>%
  mutate_if(is.numeric, funs(round(., 3))))
```

```{r}
colapsar_canasta <- function(x, sep = '-'){
  # convierte cada canasta a una cadena
  x %>% as.character %>% sort %>% paste(collapse = '-')
}
canastas_conteo <- canastas_nest %>%
                rowwise() %>%
                mutate(canasta_str = colapsar_canasta(articulos)) %>%
                group_by(canasta_str) %>%
                summarise(n = n()) %>%
                mutate(prop = round(n /num_canastas, 5)) %>%
                arrange(desc(n))
#DT::datatable
(canastas_conteo %>% head(n = 100) %>%
    mutate_if(is.numeric, funs(round(., 4))))
```

```{r}
ap <- apriori(lista_mb,
        list(supp = 0.005, target = 'frequent itemsets'))
ap
```

